CREATE TABLE COMMENT(
   ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   PARENT_ID BIGINT NOT NULL ,
   TYPE INT NOT NULL ,
   CONTENT VARCHAR(1024) NOT  NULL,
   COMMENTATOR INT NOT NULL ,
   GMT_CREATE BIGINT NOT NULL ,
   LIKE_CNT BIGINT DEFAULT 0,
   comment_cnt INT default 0
);